### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by FelixUniDa** [SKrisanski/FSCT#6]
When I try to run the the run.py with the test.las file a zero-size array shows up. Anybody faced the same issues?

### Error Message
...
Loading segmented point cloud...
Loading file... FSCT/data/test_dataset/example_FSCT_output/segmented.las
Making DTM...
### Traceback (most recent call last):
FSCT/scripts/run.py", line 67, in <module>
    clean_up_files=0)  # Optionally deletes most of the large point cloud outputs to minimise storage requirements.
FSCT/scripts/run_tools.py", line 27, in FSCT
    object_1.process_point_cloud()
FSCT/scripts/post_segmentation_script.py", line 97, in process_point_cloud
    self.DTM = self.make_DTM(crop_dtm=True)
FSCT/scripts/post_segmentation_script.py", line 55, in make_DTM
    xmin = np.floor(np.min(self.terrain_points[:, 0])) - 3
  File "<__array_function__ internals>", line 6, in amin
ib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2831, in amin
    keepdims=keepdims, initial=initial, where=where)
/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by SKrisanski** [comment]
Hi. This one sounds like the segmentation has been poor. If it performs sufficiently poorly on segmentation, you might not have any terrain points to fit a DTM to. In this case it fails. Can you please try running FSCT on the example.las file in the training data folder and see if it has the same error?

This can confirm if FSCT is installed correctly if it runs all the way through without error on this file. If it completes without issue, your problem may be data related. FSCT works on a lot of datasets, but not all. Usually it's due to insufficient point density or that nasty "smooth surface" kind of photogrammetry noise where it fails. Sometimes it's just that the data is a bit too different to what I trained it on. Let me know how it goes.

If it fails on example.las in the train folder, there is either an installation problem, or a bug in the code. I know my requirements file is causing problems, so fixing that is top of my to do list for FSCT. I'll also add some more interpretable error handling for the case of a data problem leading to no terrain points, as lots of people are getting this error. 

I'm quite time poor currently and this is now just a hobby project for me post-PhD, so it will probably be a few weeks before I can give it the time it needs, but certainly happy to try to help get you up and running in the meantime.

**Comment by SKrisanski** [comment]
Closing as I've noted the issue here: https://github.com/SKrisanski/FSCT/issues/9
More informative error handling to come for this shortly.
